# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Smart Training Log' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart Training Log

# Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

# Observable
  pod 'Observable'

# Keychain
  pod 'KeychainSwift', '~> 11.0'

# Codable Firebase interaction
  pod 'CodableFirebase'

  target 'Smart Training LogTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
